/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;


import Code.DBConnect_2;
import java.awt.Color;
import java.awt.Component;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dilshan
 */
public class addLecturers extends javax.swing.JFrame {

    /**
     * Creates new form addLecturers
     */
    public addLecturers() {
        initComponents();
        con = DBConnect_2.connect();
        //setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    
    Connection con;
    PreparedStatement pst;
    DefaultTableModel df;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        home = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        empID = new javax.swing.JTextField();
        faculty = new javax.swing.JComboBox<>();
        department = new javax.swing.JComboBox<>();
        building = new javax.swing.JComboBox<>();
        center = new javax.swing.JComboBox<>();
        lecName = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        rank = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        monday = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tuesday = new javax.swing.JTextField();
        wednesday = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        thursday = new javax.swing.JTextField();
        friday = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        saturday = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        sunday = new javax.swing.JTextField();
        monVal = new javax.swing.JLabel();
        tueVal = new javax.swing.JLabel();
        wedVal = new javax.swing.JLabel();
        thuVal = new javax.swing.JLabel();
        friVal = new javax.swing.JLabel();
        satVal = new javax.swing.JLabel();
        sunVal = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        LecNameVal = new javax.swing.JLabel();
        FacVal = new javax.swing.JLabel();
        DepVal = new javax.swing.JLabel();
        EmpIdVal = new javax.swing.JLabel();
        CenterVal = new javax.swing.JLabel();
        BuiVal = new javax.swing.JLabel();
        LevelVal = new javax.swing.JLabel();
        RankVal = new javax.swing.JLabel();
        level = new javax.swing.JComboBox<>();
        GenarateRank = new javax.swing.JButton();
        save = new javax.swing.JButton();
        ManageLecturers = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(15, 19, 52));
        jLabel1.setText("ADD LECTURER");

        home.setBackground(new java.awt.Color(15, 19, 52));
        home.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        home.setForeground(new java.awt.Color(255, 255, 255));
        home.setText("Home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        back.setBackground(new java.awt.Color(15, 19, 52));
        back.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("Back");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setName(""); // NOI18N

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel2.setText("Employee ID");

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel4.setText("Faculty");

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel5.setText("Department");

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel6.setText("Building");

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel7.setText("Rank");

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel8.setText("Level");

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel9.setText("Center");

        empID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                empIDKeyReleased(evt);
            }
        });

        faculty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Computing", "Engineering", "Business" }));

        department.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Computer Systems Engineering", "Information Technology", "Computer Science and Software Engineering" }));

        building.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "A", "B", "C", "D", "E" }));

        center.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Malabe Campus", "Metropolitan Campus", "Matara Center", "Kandy Center", "Kurunegala Center", "Jaffna Center" }));

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel10.setText("Lecturer Name");

        rank.setEditable(false);
        rank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rankActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel3.setText("Active hours of lecturer");

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel12.setText("Monday");

        monday.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mondayFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                mondayFocusLost(evt);
            }
        });
        monday.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mondayKeyReleased(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel15.setText("Tuesday");

        tuesday.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tuesdayKeyReleased(evt);
            }
        });

        wednesday.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                wednesdayKeyReleased(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel20.setText("Wednesday");

        jLabel21.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel21.setText("Thursday");

        thursday.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                thursdayKeyReleased(evt);
            }
        });

        friday.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fridayKeyReleased(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel24.setText("Friday");

        jLabel28.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel28.setText("Saturday ");

        saturday.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                saturdayKeyReleased(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel30.setText("Sunday");

        sunday.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sundayKeyReleased(evt);
            }
        });

        monVal.setForeground(new java.awt.Color(255, 51, 51));

        tueVal.setForeground(new java.awt.Color(255, 51, 51));

        wedVal.setForeground(new java.awt.Color(255, 51, 51));

        thuVal.setForeground(new java.awt.Color(255, 51, 51));

        friVal.setForeground(new java.awt.Color(255, 51, 51));

        satVal.setForeground(new java.awt.Color(255, 51, 51));

        sunVal.setForeground(new java.awt.Color(255, 51, 51));

        jLabel13.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel13.setText("* Note - Please use the 00.00 - 00.00 format when entering active hours.");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel15)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel24))
                        .addGap(83, 83, 83)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tuesday)
                            .addComponent(monday)
                            .addComponent(wednesday)
                            .addComponent(thursday)
                            .addComponent(friday, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(thuVal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(wedVal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(monVal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tueVal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(friVal, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel28))
                                .addGap(71, 71, 71)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(saturday, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(satVal, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(sunday, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sunVal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addContainerGap())
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(monday, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(saturday, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monVal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(satVal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sunVal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(tuesday, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel30)
                        .addComponent(sunday, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tueVal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(wednesday, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wedVal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(thursday, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thuVal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(friday, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(friVal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        LecNameVal.setForeground(new java.awt.Color(255, 51, 51));

        FacVal.setForeground(new java.awt.Color(255, 51, 51));

        DepVal.setForeground(new java.awt.Color(255, 51, 51));

        EmpIdVal.setForeground(new java.awt.Color(255, 51, 51));

        CenterVal.setForeground(new java.awt.Color(255, 51, 51));

        BuiVal.setForeground(new java.awt.Color(255, 51, 51));

        LevelVal.setForeground(new java.awt.Color(255, 51, 51));

        RankVal.setForeground(new java.awt.Color(255, 51, 51));

        level.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "1", "2", "3", "4", "5", "6" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(DepVal, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(RankVal, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel10))
                                .addGap(43, 43, 43)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(LecNameVal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lecName)
                                    .addComponent(empID, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                                    .addComponent(EmpIdVal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(63, 63, 63)
                                .addComponent(department, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(106, 106, 106)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FacVal, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(faculty, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rank, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(64, 64, 64)
                                    .addComponent(center, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(58, 58, 58)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(CenterVal, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(building, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(BuiVal, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(level, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(LevelVal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(center, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(lecName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LecNameVal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CenterVal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(building, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(empID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmpIdVal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BuiVal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(level, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LevelVal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(rank, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(faculty, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FacVal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(department, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DepVal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RankVal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        GenarateRank.setBackground(new java.awt.Color(15, 19, 52));
        GenarateRank.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        GenarateRank.setForeground(new java.awt.Color(255, 255, 255));
        GenarateRank.setText("Genarate Rank");
        GenarateRank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenarateRankActionPerformed(evt);
            }
        });

        save.setBackground(new java.awt.Color(15, 19, 52));
        save.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        save.setForeground(new java.awt.Color(255, 255, 255));
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        ManageLecturers.setBackground(new java.awt.Color(15, 19, 52));
        ManageLecturers.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        ManageLecturers.setForeground(new java.awt.Color(255, 255, 255));
        ManageLecturers.setText("Manage Lecturers");
        ManageLecturers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageLecturersActionPerformed(evt);
            }
        });

        clear.setBackground(new java.awt.Color(15, 19, 52));
        clear.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        clear.setForeground(new java.awt.Color(255, 255, 255));
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(15, 19, 52));
        jPanel6.setForeground(new java.awt.Color(255, 255, 255));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete_32px.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(GenarateRank, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ManageLecturers, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(81, Short.MAX_VALUE))
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ManageLecturers, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(GenarateRank, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1415, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 978, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void GenarateRankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenarateRankActionPerformed
        // TODO add your handling code here:
        if(empID.getText().trim().isEmpty()){
            EmpIdVal.setText("* Please Enter Employee ID !");
            RankVal.setText("* Please Enter Employee ID !");
        }
        else{
            EmpIdVal.setText("");
            
            String eIdPATTERN = "^[0-9]{6}$";
            Pattern eIDpatt = Pattern.compile(eIdPATTERN);
            Matcher eIDmatch = eIDpatt.matcher(empID.getText());
            if(!eIDmatch.matches()){
            EmpIdVal.setText("* Invalid Employee ID !");
            RankVal.setText("* Invalid Employee ID !");
            rank.setText("");
            }
            
            else{
                EmpIdVal.setText("");
                RankVal.setText("");
                
                if(level.getSelectedIndex() == 0){
                    RankVal.setText("* Please Select Lecturer Level !");
                }
                else{
                    RankVal.setText("");
        
                    String EmpID = empID.getText();
                    String Level = level.getSelectedItem().toString();

                    String Rank = Level + "." + EmpID ;
                    rank.setText(Rank);
                }
            }
        }
    }//GEN-LAST:event_GenarateRankActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        
        //Validations
        
        if(lecName.getText().trim().isEmpty()){
            LecNameVal.setText("* Please Enter Lecturer Name !");
        }
        else
            LecNameVal.setText("");
            
        
        if(empID.getText().trim().isEmpty()){
            EmpIdVal.setText("* Please Enter Employee ID !");
        }
        else
            EmpIdVal.setText("");
        
        if(faculty.getSelectedIndex() == 0){
            FacVal.setText("* Please Select !");
        }
        else
            FacVal.setText("");
        
        if(department.getSelectedIndex() == 0){
            DepVal.setText("* Please Select !");
        }
        else
            DepVal.setText("");
        
        if(center.getSelectedIndex() == 0){
            CenterVal.setText("* Please Select !");
        }
        else
            CenterVal.setText("");
        
        if(building.getSelectedIndex() == 0){
            BuiVal.setText("* Please Select !");
        }
        else
            BuiVal.setText("");
        
        if(level.getSelectedIndex() == 0){
            LevelVal.setText("* Please Select !");
        }
        else
            LevelVal.setText("");
        
        if(rank.getText().trim().isEmpty()){
            RankVal.setText("* Please Genarate Lecturer Rank !");
        }
        else
            RankVal.setText("");
        
        /*  if(rank.getSelectedIndex() == 0){
            RankVal.setText("* Please Select !");
        }
        else
            RankVal.setText(""); */
        
        String eIdPATTERN = "^[0-9]{6}$";
            Pattern eIDpatt = Pattern.compile(eIdPATTERN);
            Matcher eIDmatch = eIDpatt.matcher(empID.getText());
            if(!eIDmatch.matches()){
            EmpIdVal.setText("* Invalid Employee ID !");   
            }
            
            else
                EmpIdVal.setText("");
            
            
        
        
        String monPATTERN = "[0-9]{2}[.][0-9]{2}[-][0-9]{2}[.][0-9]{2}";
            Pattern monpatt = Pattern.compile(monPATTERN);
            Matcher monmatch = monpatt.matcher(monday.getText());
            if(monday.getText().trim().isEmpty() || monmatch.matches()){
            monVal.setText("");   
            }
            
            else
                monVal.setText("* Invalid Time Format !");
            
        
        String tuePATTERN = "[0-9]{2}[.][0-9]{2}[-][0-9]{2}[.][0-9]{2}";
            Pattern tuepatt = Pattern.compile(tuePATTERN);
            Matcher tuematch = tuepatt.matcher(tuesday.getText());
            if(tuesday.getText().trim().isEmpty() || tuematch.matches()){
            tueVal.setText("");   
            }
            
            else
                tueVal.setText("* Invalid Time Format !");
            
            
        String wedPATTERN = "[0-9]{2}[.][0-9]{2}[-][0-9]{2}[.][0-9]{2}";
            Pattern wedpatt = Pattern.compile(wedPATTERN);
            Matcher wedmatch = wedpatt.matcher(wednesday.getText());
            if(wednesday.getText().trim().isEmpty() || wedmatch.matches()){
            wedVal.setText("");   
            }
            
            else
                wedVal.setText("* Invalid Time Format !");
            
        
        String thuPATTERN = "[0-9]{2}[.][0-9]{2}[-][0-9]{2}[.][0-9]{2}";
            Pattern thupatt = Pattern.compile(thuPATTERN);
            Matcher thumatch = thupatt.matcher(thursday.getText());
            if(thursday.getText().trim().isEmpty() || thumatch.matches()){
            thuVal.setText("");   
            }
            
            else
                thuVal.setText("* Invalid Time Format !");
            
        String friPATTERN = "[0-9]{2}[.][0-9]{2}[-][0-9]{2}[.][0-9]{2}";
            Pattern fripatt = Pattern.compile(friPATTERN);
            Matcher frimatch = fripatt.matcher(friday.getText());
            if(friday.getText().trim().isEmpty() || frimatch.matches()){
            friVal.setText("");   
            }
            
            else
                friVal.setText("* Invalid Time Format !");
            
        String satPATTERN = "[0-9]{2}[.][0-9]{2}[-][0-9]{2}[.][0-9]{2}";
            Pattern satpatt = Pattern.compile(satPATTERN);
            Matcher satmatch = satpatt.matcher(saturday.getText());
            if(saturday.getText().trim().isEmpty() || satmatch.matches()){
            satVal.setText("");   
            }
            
            else
                satVal.setText("* Invalid Time Format !");
            
        String sunPATTERN = "[0-9]{2}[.][0-9]{2}[-][0-9]{2}[.][0-9]{2}";
            Pattern sunpatt = Pattern.compile(sunPATTERN);
            Matcher sunmatch = sunpatt.matcher(sunday.getText());
            if(sunday.getText().trim().isEmpty() || sunmatch.matches()){
            sunVal.setText("");   
            }
            
            else
                sunVal.setText("* Invalid Time Format !");    
        
        
        
        
        
        if(lecName.getText().trim().isEmpty() || empID.getText().trim().isEmpty() || !eIDmatch.matches() || faculty.getSelectedIndex() == 0 || department.getSelectedIndex() == 0 || center.getSelectedIndex() == 0 || 
                building.getSelectedIndex() == 0 || level.getSelectedIndex() == 0 || rank.getText().trim().isEmpty() ){
            Component frame = null;
            
            JOptionPane.showMessageDialog(frame, "Please fill in a valid value for all required fields");
        
        } 
        
        else{
        
        //Data Input
        
      
        try {
        
            String LecName = lecName.getText().trim();
            String EmpID = empID.getText().trim();
            String Faculty = faculty.getSelectedItem().toString();
            String Department = department.getSelectedItem().toString();
            String Center = center.getSelectedItem().toString();
            String Building = building.getSelectedItem().toString();            
            String Level = level.getSelectedItem().toString();
            String Rank = rank.getText();        
            String Monday = monday.getText().trim();
            String Tuesday = tuesday.getText().trim();
            String Wednesday = wednesday.getText().trim();
            String Thursday = thursday.getText().trim();
            String Friday = friday.getText().trim();
            String Saturday = saturday.getText().trim();
            String Sunday = sunday.getText().trim();

            
                pst = con.prepareStatement("insert into lecturers(name,emp_id,faculty,department,center,building,level,rank,monday,tuesday,wednesday,thursday,friday,saturday,sunday) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
                pst.setString(1,LecName);
                pst.setString(2,EmpID);
                pst.setString(3,Faculty);
                pst.setString(4,Department);
                pst.setString(5,Center);
                pst.setString(6,Building);
                pst.setString(7,Level);
                pst.setString(8,Rank);
                pst.setString(9,Monday);
                pst.setString(10,Tuesday);
                pst.setString(11,Wednesday);
                pst.setString(12,Thursday);
                pst.setString(13,Friday);
                pst.setString(14,Saturday);
                pst.setString(15,Sunday);
                
                pst.executeUpdate();
                
            JOptionPane.showMessageDialog(this, "New Lecturer Added Successfully");
           // this.setVisible(false);
            
            lecName.setText("");
            empID.setText("");
            faculty.setSelectedIndex(0);
            department.setSelectedIndex(0);
            center.setSelectedIndex(0);
            building.setSelectedIndex(0);
            level.setSelectedIndex(0);
            rank.setText("");
            monday.setText("");
            tuesday.setText("");
            wednesday.setText("");
            thursday.setText("");
            friday.setText("");
            saturday.setText("");
            sunday.setText("");
            
            LecNameVal.setText("");
            EmpIdVal.setText("");
            FacVal.setText("");
            DepVal.setText("");
            CenterVal.setText("");
            BuiVal.setText("");
            LevelVal.setText("");
            RankVal.setText("");
            
            } catch (SQLException ex) {
                Logger.getLogger(addLecturers.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_saveActionPerformed

    private void rankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rankActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rankActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        
            lecName.setText("");
            empID.setText("");
            faculty.setSelectedIndex(0);
            department.setSelectedIndex(0);
            center.setSelectedIndex(0);
            building.setSelectedIndex(0);
            level.setSelectedIndex(0);
            rank.setText("");
            monday.setText("");
            tuesday.setText("");
            wednesday.setText("");
            thursday.setText("");
            friday.setText("");
            saturday.setText("");
            sunday.setText("");
            
            LecNameVal.setText("");
            EmpIdVal.setText("");
            FacVal.setText("");
            DepVal.setText("");
            CenterVal.setText("");
            BuiVal.setText("");
            LevelVal.setText("");
            RankVal.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void ManageLecturersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageLecturersActionPerformed
        // TODO add your handling code here:
        ManageLecturers Mlec = new ManageLecturers();
        Mlec.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ManageLecturersActionPerformed

    private void mondayFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mondayFocusGained
        // TODO add your handling code here:
      
    }//GEN-LAST:event_mondayFocusGained

    private void mondayFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mondayFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_mondayFocusLost

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void empIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_empIDKeyReleased
        // TODO add your handling code here:
        
            rank.setText("");
            
            String eIdPATTERN = "^[0-9]{6}$";
            Pattern eIDpatt = Pattern.compile(eIdPATTERN);
            Matcher eIDmatch = eIDpatt.matcher(empID.getText());
            if(eIDmatch.matches()){
            EmpIdVal.setText("");  
            RankVal.setText("");
            }
        
    }//GEN-LAST:event_empIDKeyReleased

    private void mondayKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mondayKeyReleased
        // TODO add your handling code here:
        String monPATTERN = "[0-9]{2}[.][0-9]{2}[-][0-9]{2}[.][0-9]{2}";
            Pattern monpatt = Pattern.compile(monPATTERN);
            Matcher monmatch = monpatt.matcher(monday.getText());
            if(monday.getText().trim().isEmpty() || monmatch.matches()){
            monVal.setText("");   
            }
            
    }//GEN-LAST:event_mondayKeyReleased

    private void tuesdayKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tuesdayKeyReleased
        // TODO add your handling code here:
        String tuePATTERN = "[0-9]{2}[.][0-9]{2}[-][0-9]{2}[.][0-9]{2}";
            Pattern tuepatt = Pattern.compile(tuePATTERN);
            Matcher tuematch = tuepatt.matcher(tuesday.getText());
            if(tuesday.getText().trim().isEmpty() || tuematch.matches()){
            tueVal.setText("");
            }
    }//GEN-LAST:event_tuesdayKeyReleased

    private void wednesdayKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_wednesdayKeyReleased
        // TODO add your handling code here:
        String wedPATTERN = "[0-9]{2}[.][0-9]{2}[-][0-9]{2}[.][0-9]{2}";
            Pattern wedpatt = Pattern.compile(wedPATTERN);
            Matcher wedmatch = wedpatt.matcher(wednesday.getText());
            if(wednesday.getText().trim().isEmpty() || wedmatch.matches()){
            wedVal.setText("");   
            }
    }//GEN-LAST:event_wednesdayKeyReleased

    private void thursdayKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_thursdayKeyReleased
        // TODO add your handling code here:
        String thuPATTERN = "[0-9]{2}[.][0-9]{2}[-][0-9]{2}[.][0-9]{2}";
            Pattern thupatt = Pattern.compile(thuPATTERN);
            Matcher thumatch = thupatt.matcher(thursday.getText());
            if(thursday.getText().trim().isEmpty() || thumatch.matches()){
            thuVal.setText("");   
            }
    }//GEN-LAST:event_thursdayKeyReleased

    private void fridayKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fridayKeyReleased
        // TODO add your handling code here:
        String friPATTERN = "[0-9]{2}[.][0-9]{2}[-][0-9]{2}[.][0-9]{2}";
            Pattern fripatt = Pattern.compile(friPATTERN);
            Matcher frimatch = fripatt.matcher(friday.getText());
            if(friday.getText().trim().isEmpty() || frimatch.matches()){
            friVal.setText("");   
            }
    }//GEN-LAST:event_fridayKeyReleased

    private void saturdayKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_saturdayKeyReleased
        // TODO add your handling code here:
        String satPATTERN = "[0-9]{2}[.][0-9]{2}[-][0-9]{2}[.][0-9]{2}";
            Pattern satpatt = Pattern.compile(satPATTERN);
            Matcher satmatch = satpatt.matcher(saturday.getText());
            if(saturday.getText().trim().isEmpty() || satmatch.matches()){
            satVal.setText("");   
            }
    }//GEN-LAST:event_saturdayKeyReleased

    private void sundayKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sundayKeyReleased
        // TODO add your handling code here:
        String sunPATTERN = "[0-9]{2}[.][0-9]{2}[-][0-9]{2}[.][0-9]{2}";
            Pattern sunpatt = Pattern.compile(sunPATTERN);
            Matcher sunmatch = sunpatt.matcher(sunday.getText());
            if(sunday.getText().trim().isEmpty() || sunmatch.matches()){
            sunVal.setText("");   
            }
    }//GEN-LAST:event_sundayKeyReleased

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        Home home = new Home();
        home.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addLecturers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addLecturers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addLecturers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addLecturers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addLecturers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BuiVal;
    private javax.swing.JLabel CenterVal;
    private javax.swing.JLabel DepVal;
    private javax.swing.JLabel EmpIdVal;
    private javax.swing.JLabel FacVal;
    private javax.swing.JButton GenarateRank;
    private javax.swing.JLabel LecNameVal;
    private javax.swing.JLabel LevelVal;
    private javax.swing.JButton ManageLecturers;
    private javax.swing.JLabel RankVal;
    private javax.swing.JButton back;
    private javax.swing.JComboBox<String> building;
    private javax.swing.JComboBox<String> center;
    private javax.swing.JButton clear;
    private javax.swing.JComboBox<String> department;
    private javax.swing.JTextField empID;
    private javax.swing.JComboBox<String> faculty;
    private javax.swing.JLabel friVal;
    private javax.swing.JTextField friday;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField lecName;
    private javax.swing.JComboBox<String> level;
    private javax.swing.JLabel monVal;
    private javax.swing.JTextField monday;
    private javax.swing.JTextField rank;
    private javax.swing.JLabel satVal;
    private javax.swing.JTextField saturday;
    private javax.swing.JButton save;
    private javax.swing.JLabel sunVal;
    private javax.swing.JTextField sunday;
    private javax.swing.JLabel thuVal;
    private javax.swing.JTextField thursday;
    private javax.swing.JLabel tueVal;
    private javax.swing.JTextField tuesday;
    private javax.swing.JLabel wedVal;
    private javax.swing.JTextField wednesday;
    // End of variables declaration//GEN-END:variables
}
