/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Code.DBconect;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Kasun Deeptha
 */
public class manageTag extends javax.swing.JFrame {

    private static Statement st;
    Connection conn = null;
    ResultSet rs = null;
    /**
     * Creates new form mageTag
     */
    public manageTag() {
        initComponents();
        st=DBconect.connect();
        tableload();
    }
    
    public void tableload() {
    
        try {
            String sql = "SELECT id AS ID,tagName AS 'TAG NAME',tagCode AS 'TAG CODE',relatedTag AS 'RELATED TAG' FROM tag";
            rs = st.executeQuery(sql);
            tagTable.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }
    
    public void tabledata() {
    
        int r = tagTable.getSelectedRow();
        
        String tagName = tagTable.getValueAt(r, 1).toString();
        String tagCode = tagTable.getValueAt(r,2).toString();
        String relatedTag = tagTable.getValueAt(r, 1).toString();
        
        tagNameBox.setText(tagName);
        tagCodeBox.setText(tagCode);
        relatedTagBox.setSelectedItem(relatedTag);
        
    }
    
    public void clear() {
        
        tagNameBox.setText("");
        tagCodeBox.setText("");
        relatedTagBox.setSelectedIndex(0);
    
    }
    
    public void update() {
    
        int r = tagTable.getSelectedRow();
        int value = (int) (tagTable.getModel().getValueAt(r, 0));
        
        String tagName = tagNameBox.getText();
        int tagCode = Integer.parseInt(tagCodeBox.getText());
        String relatedTag = relatedTagBox.getSelectedItem().toString();
        
        try {
            String sql = "UPDATE tag SET tagName='"+tagName+"',tagCode='"+tagCode+"',relatedTag='"+relatedTag+"' "
                    + "WHERE id='"+value+"'";
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Tag updated successfully");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
        
        tableload();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tagTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        tagNameBox = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tagCodeBox = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        relatedTagBox = new javax.swing.JComboBox<>();
        clearBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        codeV = new javax.swing.JLabel();
        nameV = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1370, 700));
        setMinimumSize(new java.awt.Dimension(1370, 700));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tagTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tagTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tagTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tagTableMouseClicked(evt);
            }
        });
        tagTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tagTableKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tagTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 1340, 180));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Tag name");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        tagNameBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tagNameBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tagNameBoxActionPerformed(evt);
            }
        });
        tagNameBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tagNameBoxKeyReleased(evt);
            }
        });
        jPanel1.add(tagNameBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 100, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Tag code");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        tagCodeBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tagCodeBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tagCodeBoxKeyReleased(evt);
            }
        });
        jPanel1.add(tagCodeBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 100, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Related tag");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));

        relatedTagBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        relatedTagBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lecture", "Tutorial", "Lab", "Evalution" }));
        jPanel1.add(relatedTagBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 100, -1));

        clearBtn.setBackground(new java.awt.Color(15, 19, 52));
        clearBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clearBtn.setForeground(new java.awt.Color(255, 255, 255));
        clearBtn.setText("CLEAR");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });
        jPanel1.add(clearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 90, -1));

        updateBtn.setBackground(new java.awt.Color(15, 19, 52));
        updateBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn.setText("UPDATE");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        jPanel1.add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 210, 90, -1));

        deleteBtn.setBackground(new java.awt.Color(15, 19, 52));
        deleteBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setText("DELETE");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        jPanel1.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 260, 90, -1));

        addBtn.setBackground(new java.awt.Color(15, 19, 52));
        addBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBtn.setText("ADD");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        jPanel1.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 160, 90, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Manage  Tag");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, 240, 50));

        jButton1.setForeground(new java.awt.Color(15, 19, 52));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home_24px.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 40, 40));

        codeV.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        codeV.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(codeV, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 210, 90, 20));

        nameV.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nameV.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(nameV, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 160, 90, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1370, 700));

        jPanel2.setBackground(new java.awt.Color(15, 19, 52));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete_32px.png"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1326, 0, 40, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -2, 1370, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tagTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tagTableMouseClicked
        // TODO add your handling code here:
        tabledata();
    }//GEN-LAST:event_tagTableMouseClicked

    private void tagTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tagTableKeyReleased
        // TODO add your handling code here:
        tabledata();
    }//GEN-LAST:event_tagTableKeyReleased

    private void tagNameBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tagNameBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tagNameBoxActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_clearBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        update();
        tableload();
    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:

        int check = JOptionPane.showConfirmDialog(null, "Do you want to delete?");
        int r = tagTable.getSelectedRow();
        int value = (int) (tagTable.getModel().getValueAt(r, 0));

        if(check == 0){

            try {
                String sql = "DELETE FROM tag WHERE id='"+value+"'";
                st.executeUpdate(sql);st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Tag deleted successfully");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }

            tableload();

        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed

        String tagName = tagNameBox.getText();
        int tagCode = Integer.parseInt(tagCodeBox.getText());
        String relatedTag = relatedTagBox.getSelectedItem().toString();

        try {
            String sql = "INSERT INTO tag(tagName,tagCode,relatedTag) VALUES ('"+tagName+"','"+tagCode+"','"+relatedTag+"')";
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Tag added successfully");
        } catch (Exception e) {
        }
        
        tableload();
    }//GEN-LAST:event_addBtnActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Home h = new Home();
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tagNameBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tagNameBoxKeyReleased
        // TODO add your handling code here:
        String PATTERN ="^[a-zA-Z]{1,100}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(tagNameBox.getText());
        if(!match.matches()){
            nameV.setText("Incorrect input");
        }else{
            nameV.setText(null);
        }
    }//GEN-LAST:event_tagNameBoxKeyReleased

    private void tagCodeBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tagCodeBoxKeyReleased
        // TODO add your handling code here:
        String PATTERN ="^[0-9]{1,10}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(tagCodeBox.getText());
        if(!match.matches()){
            codeV.setText("Incorrect input");
        }else{
            codeV.setText(null);
        }
    }//GEN-LAST:event_tagCodeBoxKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manageTag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manageTag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manageTag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manageTag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manageTag().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton clearBtn;
    private javax.swing.JLabel codeV;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameV;
    private javax.swing.JComboBox<String> relatedTagBox;
    private javax.swing.JTextField tagCodeBox;
    private javax.swing.JTextField tagNameBox;
    private javax.swing.JTable tagTable;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
