/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author Kasun Deeptha
 */
import Code.DBconect;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

public class SessionManagement extends javax.swing.JFrame {

    
    private static Statement st;
    PreparedStatement pst = null;
    Connection conn = null;
    ResultSet rs = null;
    /**
     * Creates new form SessionManagement
     */
    public SessionManagement() {
        initComponents();
        st= DBconect.connect();
        session1();
        session2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        session2 = new javax.swing.JComboBox<>();
        session1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        viewConsecutive = new javax.swing.JButton();
        addConsecutive = new javax.swing.JButton();
        addParellel = new javax.swing.JButton();
        viewParellel = new javax.swing.JButton();
        addOverlaping = new javax.swing.JButton();
        viewOverlaping = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(15, 19, 52));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete_32px.png"))); // NOI18N
        jLabel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 0, 40, 30));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(710, 383));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Session Management");
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 440, 50));

        jButton1.setForeground(new java.awt.Color(15, 19, 52));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home_24px.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 40, 40));

        jButton2.setForeground(new java.awt.Color(15, 19, 52));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/back_to_30px.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 40, 40));

        session2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        session2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                session2ActionPerformed(evt);
            }
        });
        jPanel1.add(session2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 300, 450, 50));

        session1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        session1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                session1ActionPerformed(evt);
            }
        });
        jPanel1.add(session1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 420, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Session 2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 230, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Session 1");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, -1, -1));

        viewConsecutive.setBackground(new java.awt.Color(15, 19, 52));
        viewConsecutive.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        viewConsecutive.setForeground(new java.awt.Color(255, 255, 255));
        viewConsecutive.setText("VIEW CONSECUTIVE");
        viewConsecutive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewConsecutiveActionPerformed(evt);
            }
        });
        jPanel1.add(viewConsecutive, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 570, 230, 50));

        addConsecutive.setBackground(new java.awt.Color(15, 19, 52));
        addConsecutive.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        addConsecutive.setForeground(new java.awt.Color(255, 255, 255));
        addConsecutive.setText("ADD CONSECUTIVE");
        addConsecutive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addConsecutiveActionPerformed(evt);
            }
        });
        jPanel1.add(addConsecutive, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, 230, 50));

        addParellel.setBackground(new java.awt.Color(15, 19, 52));
        addParellel.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        addParellel.setForeground(new java.awt.Color(255, 255, 255));
        addParellel.setText("ADD PARELLEL");
        addParellel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addParellelActionPerformed(evt);
            }
        });
        jPanel1.add(addParellel, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 470, 230, 50));

        viewParellel.setBackground(new java.awt.Color(15, 19, 52));
        viewParellel.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        viewParellel.setForeground(new java.awt.Color(255, 255, 255));
        viewParellel.setText("VIEW PARELLEL");
        viewParellel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewParellelActionPerformed(evt);
            }
        });
        jPanel1.add(viewParellel, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 570, 230, 50));

        addOverlaping.setBackground(new java.awt.Color(15, 19, 52));
        addOverlaping.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        addOverlaping.setForeground(new java.awt.Color(255, 255, 255));
        addOverlaping.setText("ADD OVERLAPING");
        addOverlaping.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOverlapingActionPerformed(evt);
            }
        });
        jPanel1.add(addOverlaping, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 470, 230, 50));

        viewOverlaping.setBackground(new java.awt.Color(15, 19, 52));
        viewOverlaping.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        viewOverlaping.setForeground(new java.awt.Color(255, 255, 255));
        viewOverlaping.setText("VIEW OVERLAPING");
        viewOverlaping.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOverlapingActionPerformed(evt);
            }
        });
        jPanel1.add(viewOverlaping, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 570, 230, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1367, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Home h = new Home();
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Home h = new Home();
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void addConsecutiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addConsecutiveActionPerformed
        
        String session_1 = session1.getSelectedItem().toString();
        String session_2 = session2.getSelectedItem().toString();
        
        String[] array1 = session_1.split("/");
        String[] array2 = session_2.split("/");
        
        String s1_lecture1 = array1[0];
        String s1_lecture2 = array1[1];
        String s1_subjectcode = array1[2];
        String s1_subjectname = array1[3];
        String s1_groupid = array1[4];
        String s1_tag = array1[5];
        
        String s2_lecture1 = array2[0];
        String s2_lecture2 = array2[1];
        String s2_subjectcode = array2[2];
        String s2_subjectname = array2[3];
        String s2_groupid = array2[4];
        String s2_tag = array2[5];
        try {
            String sql = "INSERT INTO consecutive_sessions (s1_lecture1 ,s1_lecture2,s1_subjectcode,s1_subjectname,s1_groupid,"
                    + "s1_tag,s2_lecture1,s2_lecture2,s2_subjectcode,s2_subjectname,s2_groupid,s2_tag)"
                    + " VALUES('"+s1_lecture1+"','"+s1_lecture2+"','"+s1_subjectcode+"','"+s1_subjectname+"','"+s1_groupid+"',"
                    + "'"+s1_tag+"','"+s2_lecture1+"','"+s2_lecture2+"','"+s2_subjectcode+"','"+s2_subjectname+"',"
                    + "'"+s2_groupid+"','"+s2_tag+"')";
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Consecutive session added successfully");
            
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_addConsecutiveActionPerformed

    private void addParellelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addParellelActionPerformed
        String session_1 = session1.getSelectedItem().toString();
        String session_2 = session2.getSelectedItem().toString();
        
        String[] array1 = session_1.split("/");
        String[] array2 = session_2.split("/");
        
        String s1_lecture1 = array1[0];
        String s1_lecture2 = array1[1];
        String s1_subjectcode = array1[2];
        String s1_subjectname = array1[3];
        String s1_groupid = array1[4];
        String s1_tag = array1[5];
        
        String s2_lecture1 = array2[0];
        String s2_lecture2 = array2[1];
        String s2_subjectcode = array2[2];
        String s2_subjectname = array2[3];
        String s2_groupid = array2[4];
        String s2_tag = array2[5];
        try {
            String sql = "INSERT INTO parellel_session (s1_lecture1 ,s1_lecture2,s1_subjectcode,s1_subjectname,s1_groupid,"
                    + "s1_tag,s2_lecture1,s2_lecture2,s2_subjectcode,s2_subjectname,s2_groupid,s2_tag)"
                    + " VALUES('"+s1_lecture1+"','"+s1_lecture2+"','"+s1_subjectcode+"','"+s1_subjectname+"','"+s1_groupid+"',"
                    + "'"+s1_tag+"','"+s2_lecture1+"','"+s2_lecture2+"','"+s2_subjectcode+"','"+s2_subjectname+"',"
                    + "'"+s2_groupid+"','"+s2_tag+"')";
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Parellel session added successfully");
            
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_addParellelActionPerformed

    private void addOverlapingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOverlapingActionPerformed
        addparellel();
    }//GEN-LAST:event_addOverlapingActionPerformed

    private void session1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_session1ActionPerformed
        
      // session1();
         
    }//GEN-LAST:event_session1ActionPerformed

    private void session2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_session2ActionPerformed
        //session2();
    }//GEN-LAST:event_session2ActionPerformed

    private void viewConsecutiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewConsecutiveActionPerformed
        CosecutiveSession c = new CosecutiveSession();
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_viewConsecutiveActionPerformed

    private void viewParellelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewParellelActionPerformed
        ParellelSession p  = new ParellelSession();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_viewParellelActionPerformed

    private void viewOverlapingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOverlapingActionPerformed
        OverlapSession o  = new OverlapSession();
        o.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_viewOverlapingActionPerformed

    public void session1(){
    
        try {
            String sql = "SELECT * FROM sessions";
            rs = st.executeQuery(sql);
            
            while(rs.next()){
            
                String lecture1 = rs.getString("Lecturer_1");
                String lecture2 = rs.getString("Lecturer_2");
                String subCode = rs.getString("Subject_Code");
                String subName = rs.getString("Subject_Name");
                String grpId = rs.getString("Group_ID");
                String tag = rs.getString("Tag");
                
                session1.addItem(lecture1+"/"+lecture2+"/"+subCode+"/"+subName+"/"+grpId+"/"+tag);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,e);
        }
    
    }
    
    public void session2(){
    
        try {
            String sql = "SELECT * FROM sessions";
            rs = st.executeQuery(sql);
            
            while(rs.next()){
            
                String lecture1 = rs.getString("Lecturer_1");
                String lecture2 = rs.getString("Lecturer_2");
                String subCode = rs.getString("Subject_Code");
                String subName = rs.getString("Subject_Name");
                String grpId = rs.getString("Group_ID");
                String tag = rs.getString("Tag");
                
                session2.addItem(lecture1+"/"+lecture2+"/"+subCode+"/"+subName+"/"+grpId+"/"+tag);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,e);
        }
    
    }
    
    public void addparellel() {
    
        String session_1 = session1.getSelectedItem().toString();
        String session_2 = session2.getSelectedItem().toString();
        
        String[] array1 = session_1.split("/");
        String[] array2 = session_2.split("/");
        
        String s1_lecture1 = array1[0];
        String s1_lecture2 = array1[1];
        String s1_subjectcode = array1[2];
        String s1_subjectname = array1[3];
        String s1_groupid = array1[4];
        String s1_tag = array1[5];
        
        String s2_lecture1 = array2[0];
        String s2_lecture2 = array2[1];
        String s2_subjectcode = array2[2];
        String s2_subjectname = array2[3];
        String s2_groupid = array2[4];
        String s2_tag = array2[5];
        try {
            String sql = "INSERT INTO overlap_session (s1_lecture1 ,s1_lecture2,s1_subjectcode,s1_subjectname,s1_groupid,"
                    + "s1_tag,s2_lecture1,s2_lecture2,s2_subjectcode,s2_subjectname,s2_groupid,s2_tag)"
                    + " VALUES('"+s1_lecture1+"','"+s1_lecture2+"','"+s1_subjectcode+"','"+s1_subjectname+"','"+s1_groupid+"',"
                    + "'"+s1_tag+"','"+s2_lecture1+"','"+s2_lecture2+"','"+s2_subjectcode+"','"+s2_subjectname+"',"
                    + "'"+s2_groupid+"','"+s2_tag+"')";
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Non-Overlap session added successfully");
            
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, e);
        }
    }                                              

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SessionManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SessionManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SessionManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SessionManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SessionManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addConsecutive;
    private javax.swing.JButton addOverlaping;
    private javax.swing.JButton addParellel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> session1;
    private javax.swing.JComboBox<String> session2;
    private javax.swing.JButton viewConsecutive;
    private javax.swing.JButton viewOverlaping;
    private javax.swing.JButton viewParellel;
    // End of variables declaration//GEN-END:variables
}
